### ISSUE TITLE
playerPositions vector being empty

### ISSUE THREAD

**Issue by idk28-sv** [carlgwastaken/cs2-external-aimbot#3]
Basically when I try to run the project, it just says "playerPositions vector was empty" and doesnt work because of it. What can I do?

![image](https://github.com/carlgwastaken/cs2-external-aimbot/assets/174922385/628bfd3a-9655-417c-82b4-461a790fc37a)

**Comment by carlgwastaken** [comment]
well, after reading the closed issues you can try this updating your offsets

**Comment by asientador** [comment]
I updated the offsets and it's still saying playerPositions vector was empty. Came from the YouTube tutorial, really good info about the subject and perfect entry point for newbies like me.

`namespace offset {

	constexpr std::ptrdiff_t dwEntityList = 0x19BDD58;
	constexpr std::ptrdiff_t dwViewMatrix = 0x1A1FCB0;
	constexpr std::ptrdiff_t dwLocalPlayerPawn = 0x1823A08;


	constexpr std::ptrdiff_t m_hPawn = 0x5FC;


	constexpr std::ptrdiff_t m_iHealth = 0x324;
	constexpr std::ptrdiff_t m_iTeamNum = 0x3C3;


	constexpr std::ptrdiff_t m_vOldOrigin = 0x1274;


	constexpr std::ptrdiff_t m_entitySpottedState = 0x2288;
}`

**Comment by asientador** [comment]
My apologies, I was building it on x86 when it should have been built on x64. Sorry for the confusion, everyone. Thanks a lot for sharing the video and the source—perfect for learning @idk28-sv

**Comment by carlgwastaken** [comment]
it happens to the best of us, have fun!
