### ISSUE TITLE
Aimbot isn't working anymore after the recent update!

### ISSUE THREAD

**Issue by DEFS9** [carlgwastaken/cs2-external-aimbot#5]
playerPositions vector was empty!!! 

It was working fine! i just updated the offsets for latest update and it longer working!
I think something is changed!!!
![8Pq4OzC](https://github.com/user-attachments/assets/dd8febb8-f6d6-4f15-83d3-dcb8bb207e5b)

**Comment by carlgwastaken** [comment]
you should be using m_hPlayerPawn, test that and then tell me if it works!

**Comment by DEFS9** [comment]
> you should be using m_hPlayerPawn, test that and then tell me if it works!

Sadly, not working :(! any fix?

**Comment by DEFS9** [comment]
Any suggestions?

**Comment by carlgwastaken** [comment]
Unfortunately not, if the code isn't working and neither is updating offsets, then i can't really help from here. debug and test
